### ISSUE TITLE
Planing the menu on the left

### ISSUE THREAD

**Issue by drfurtado** [grantmcdermott/quarto-revealjs-clean#12]
I added the following in my yaml, but it did not do the trick. Any solutions? Also, I want to be able to control the position of the page numbers. By default, it is placed on the top-right of the slide.

```
format: clean-revealjs
menu: 
  side: left
```

**Comment by grantmcdermott** [comment]
I've hardcoded the menu on the top right as part of the theme SCSS here: https://github.com/grantmcdermott/quarto-revealjs-clean/blob/main/_extensions/clean/clean.scss#L180

If you don't plan to add/use any other widgets (chalkboard etc.) then I think changing `right: 0` on line 185 to `left: 0` should suffice as a simple workaround hack.

For moving page numbers, you'll have to add some custom SCSS to override the revealjs defaults. Should be pretty easy to do (and I'm sure ChatGPT etc. will have good suggestions if nothing comes up on stackoverflow etc.)

Closing, but please open if my suggestions don't work.
