### ISSUE TITLE
Outdated version number in extension YAML

### ISSUE THREAD

**Issue by harrysw1729** [grantmcdermott/quarto-revealjs-clean#14]
The version number in the extension YAML [here](https://github.com/grantmcdermott/quarto-revealjs-clean/blob/0aa8273ad7c77b7f6a9d6ba5e9b7abd240bdc335/_extensions/clean/_extension.yml#L3) is still `1.0.0`. Could it please be updated so it is easier to tell whether an update is available from the YAML?

Thanks for your help! 😄

**Comment by grantmcdermott** [comment]
Good catch, thanks!
